title: Shawn Jim
description: 北方に魚がいます,その名は塩です。
baseurl: ""
url: https://shawnjim.github.io/

theme: cvless

# site settings
taglong: 当兔子开始奔跑
tagshort: 简历

# author settings
author:
  name: Shawn Jim <金振潇>
  email: jinzhenxiao@apache.org
photo: assets/files/photo.jpg
address: Shenzheng China
phone: +86 155 0253 1057

# social media links
social:
  github: ShawnJim
  x: ulShawnjim
#  facebook: username
#  instagram: username
#  linkedin: username
#  stackoverflow: 0000000/username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
