title: Shawn Jim
description:
baseurl: ""
url: https://shawnjim.com

theme: cvless

# site settings
taglong: 当兔子坐上蒸汽列车
tagshort:  蒸汽兔

# author settings
author:
  name: Shawn Jim
  email: jinzhenxiao@apache.org
photo: assets/files/photo.jpg
address: Shenzheng China
phone: +86 155 0253 1057

# social media links
social:
  github: ShawnJim
  x: ulShawnjim
  stackoverflow: 12645351/shawn-jim
#  facebook: username
#  instagram: username
#  linkedin: username

# collections
customer-collections:
  - backend
  - distributed-operational
  - bigdata
  - note
  - posts
  - thinking
  - data-structures-with-algorithms

collections:
  backend:
    name: 后端框架
    output: true
    sub:
      - springboot
      - jvm
      - multithreading
  distributed-operational:
    name: 分布式 & 运维
    output: true
    sub:
      - k8s
  bigdata:
    name: 大数据
    order:
      - 2023-07-23-Kudu读&写表异常问题修复&总结.md
    output: true
  note:
    name: 笔记
    output: true
    sub:
      - linux
      - interview
  posts:
    name: 归档
    output: true
  springboot:
    name: SpringBoot
    order:
      - 2019-07-12-初识SpringBoot-第一篇_创建一个SpringBoot工程.md
      - 2019-07-19-初识SpringBoot-第二篇_配置文件详解.md
      - 2019-07-24-初识SpringBoot-第三篇_日志相关整合.md
      - 2019-07-26-初识SpringBoot-第四篇_整合thymeleaf-国际化配置.md
      - 2019-07-26-初识SpringBoot-第五篇_Spring-MVC配置及原理-拦截器应用.md
      - 2019-07-27-初识SpringBoot-第六篇_使用jdbcTemplate访问数据库.md
      - 2019-07-27-初识SpringBoot-第七篇_Mybatis整合.md
      - 2019-07-30-初识SpringBoot-第八篇_SpringDataJpa整合.md
      - 2019-07-31-初识SpringBoot-第九篇_自定义Starter.md
    output: true
  k8s:
    name: K8s
    order:
      - 2020-06-20-初探k8s-阿里云安装k8s公网ip部署(一).md
      - 2020-07-04-初探k8s-安装CNI网络插件calico(二).md
      - 2020-07-04-初探k8s-通过资源文件部署应用(三).md
      - 2020-07-05-初探k8s-安装nginx-ingress控制器(四).md
      - 2020-07-05-初探k8s-准备数据卷(五).md
      - 2020-07-05-初探k8s-使用数据卷(六).md
      - 2020-07-05-初探k8s-ConfigMap外部化配置(七).md
      - 2020-07-05-初探k8s-kubernetes-dashboard管理(八).md
    output: true
  linux:
    name: linux中间件相关
    output: true
  interview:
    name: 面试相关
    output: true
  jvm:
    name: jvm
    output: true
  multithreading:
    name: 多线程
    output: true
  thinking:
    name: 阅读 & 思考
    output: true
  data-structures-with-algorithms:
    name: 数据结构与算法
    output: true


# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
